# Generated by Django 5.2.6 on 2025-10-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="ai_keywords",
            field=models.CharField(
                blank=True, help_text="AI-generated keywords", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="ai_summary",
            field=models.TextField(blank=True, help_text="AI-generated review summary"),
        ),
    ]
