# Generated by Django 5.2.6 on 2025-10-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_ai_keywords_review_ai_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="ai_emerging_topics",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-identified emerging topics and trends",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="ai_issues_identified",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-identified main issues and concerns",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="ai_negative_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-generated negative keywords list",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="ai_positive_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-generated positive keywords list",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="ai_topics_analysis",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="AI-generated topic metrics and analysis",
            ),
        ),
    ]
