# Generated by Django 5.2.6 on 2025-10-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_aianalysissession_delete_aianalysiscache"),
    ]

    operations = [
        migrations.AddField(
            model_name="aianalysissession",
            name="ai_recommendations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-generated business recommendations",
            ),
        ),
    ]
