# Generated by Django 5.2.6 on 2025-10-08 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_alter_aianalysisresult_analysis_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("manager", "Hotel Manager"),
                            ("viewer", "Viewer"),
                        ],
                        db_index=True,
                        default="viewer",
                        help_text="User's role determining access permissions",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department or position", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="User account status"),
                ),
                (
                    "additional_hotels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional hotels this user can access",
                        related_name="additional_staff",
                        to="reviews.hotel",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary hotel association (null for super admins)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="reviews.hotel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated Django user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["user__username"],
                "indexes": [
                    models.Index(fields=["role"], name="reviews_use_role_9da56a_idx"),
                    models.Index(
                        fields=["hotel", "role"], name="reviews_use_hotel_i_d94d0e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="reviews_use_is_acti_46edb3_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role__in", ["admin", "manager", "viewer"])
                        ),
                        name="valid_user_role",
                    )
                ],
            },
        ),
    ]
