# Generated by Django 5.2.6 on 2025-10-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0011_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
