# Generated by Django 5.2.6 on 2025-10-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_add_ai_tags_analysis_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_type", models.CharField(default="combined", max_length=50)),
                ("days_range", models.PositiveIntegerField(default=30)),
                (
                    "summary_analysis",
                    models.JSONField(
                        default=dict, help_text="Cached summary analysis results"
                    ),
                ),
                (
                    "tags_analysis",
                    models.JSONField(
                        default=dict, help_text="Cached tags analysis results"
                    ),
                ),
                ("total_reviews_analyzed", models.PositiveIntegerField(default=0)),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis_type", "days_range", "hotel"],
                        name="reviews_aia_analysi_f5576c_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="reviews_aia_created_5fd240_idx"
                    ),
                ],
            },
        ),
    ]
