# Generated by Django 4.2.7 on 2025-10-02 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_aianalysiscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated comprehensive summary')),
                ('ai_positive_keywords', models.JSONField(blank=True, default=list, help_text='AI-identified positive keywords')),
                ('ai_negative_keywords', models.JSONField(blank=True, default=list, help_text='AI-identified negative keywords')),
                ('ai_topics_analysis', models.JSONField(blank=True, default=dict, help_text='AI-generated comprehensive topics analysis')),
                ('ai_issues_identified', models.JSONField(blank=True, default=list, help_text='AI-identified main issues and concerns')),
                ('ai_emerging_topics', models.JSONField(blank=True, default=list, help_text='AI-identified emerging topics and trends')),
                ('analysis_date_range', models.JSONField(default=dict, help_text='Date range used for analysis')),
                ('total_reviews_analyzed', models.PositiveIntegerField(default=0)),
                ('generation_duration', models.FloatField(blank=True, help_text='Time taken to generate analysis in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.DeleteModel(
            name='AIAnalysisCache',
        ),
    ]
