# Generated by Django 5.2.6 on 2025-10-08 03:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_postgresql_optimizations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIAnalysisSession",
        ),
        migrations.RemoveField(
            model_name="reviewsummary",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="searchquery",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="reviewsource",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="reviews_rev_sentime_2cb35a_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="reviews_rev_ai_scor_c65bc1_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="reviews_rev_date_po_8efc43_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="reviews_rev_hotel_i_02ca71_idx",
        ),
        migrations.RenameField(
            model_name="reviewsource",
            old_name="api_endpoint",
            new_name="website_url",
        ),
        migrations.RemoveField(
            model_name="review",
            name="ai_emerging_topics",
        ),
        migrations.RemoveField(
            model_name="review",
            name="ai_issues_identified",
        ),
        migrations.RemoveField(
            model_name="review",
            name="ai_negative_keywords",
        ),
        migrations.RemoveField(
            model_name="review",
            name="ai_positive_keywords",
        ),
        migrations.RemoveField(
            model_name="review",
            name="ai_topics_analysis",
        ),
        migrations.RemoveField(
            model_name="reviewsource",
            name="url",
        ),
        migrations.AddField(
            model_name="hotel",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="ai_topics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="AI-identified topics and their relevance scores",
            ),
        ),
        migrations.AddField(
            model_name="reviewbatch",
            name="file_size",
            field=models.PositiveIntegerField(
                default=0, help_text="File size in bytes"
            ),
        ),
        migrations.AlterField(
            model_name="agenttask",
            name="input_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="agenttask",
            name="output_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="review",
            name="ai_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-extracted keywords from review text",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="ai_score",
            field=models.FloatField(
                default=3.0,
                help_text="AI-generated sentiment score (0-5 scale)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="ai_summary",
            field=models.TextField(
                blank=True, help_text="AI-generated summary of the review"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="confidence_score",
            field=models.FloatField(
                default=0.5,
                help_text="AI confidence in analysis (0-1 scale)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="date_posted",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="original_rating",
            field=models.FloatField(
                blank=True,
                help_text="Original rating from review platform (0-5 scale)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="processed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                db_index=True,
                default="neutral",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="reviews.reviewsource"
            ),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(
                fields=["status", "created_at"], name="reviews_age_status_b0a7b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(
                fields=["agent_name", "created_at"],
                name="reviews_age_agent_n_0e0265_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hotel",
            index=models.Index(fields=["name"], name="reviews_hot_name_cae81b_idx"),
        ),
        migrations.AddIndex(
            model_name="hotel",
            index=models.Index(
                fields=["location"], name="reviews_hot_locatio_84b749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["sentiment", "ai_score"], name="reviews_rev_sentime_171749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["hotel", "sentiment"], name="reviews_rev_hotel_i_cc4517_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["date_posted", "sentiment"],
                name="reviews_rev_date_po_23efd0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["processed", "created_at"],
                name="reviews_rev_process_4db0eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["hotel", "date_posted"], name="reviews_rev_hotel_i_ea04da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewbatch",
            index=models.Index(
                fields=["status", "upload_date"], name="reviews_rev_status_4b03d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewbatch",
            index=models.Index(
                fields=["uploaded_by", "upload_date"],
                name="reviews_rev_uploade_5eda37_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="hotel",
            constraint=models.UniqueConstraint(
                fields=("name", "location"), name="unique_hotel_location"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("ai_score__gte", 0.0), ("ai_score__lte", 5.0)),
                name="valid_ai_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence_score__gte", 0.0), ("confidence_score__lte", 1.0)
                ),
                name="valid_confidence_range",
            ),
        ),
        migrations.DeleteModel(
            name="ReviewSummary",
        ),
        migrations.DeleteModel(
            name="SearchQuery",
        ),
    ]
