# Generated by Django 5.2.6 on 2025-10-08 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reviews",
            "0008_delete_aianalysissession_remove_reviewsummary_hotel_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("combined", "Combined Analysis"),
                            ("summary", "Summary Only"),
                            ("sentiment", "Sentiment Analysis"),
                            ("tags", "Tags Analysis"),
                        ],
                        default="combined",
                        help_text="Type of AI analysis performed",
                        max_length=50,
                    ),
                ),
                (
                    "days_analyzed",
                    models.PositiveIntegerField(
                        default=30, help_text="Number of days of data analyzed"
                    ),
                ),
                (
                    "date_range_start",
                    models.DateField(help_text="Start date of analysis period"),
                ),
                (
                    "date_range_end",
                    models.DateField(help_text="End date of analysis period"),
                ),
                (
                    "total_reviews_analyzed",
                    models.PositiveIntegerField(help_text="Number of reviews analyzed"),
                ),
                (
                    "summary_data",
                    models.JSONField(
                        default=dict, help_text="AI-generated summary and insights"
                    ),
                ),
                (
                    "sentiment_analysis",
                    models.JSONField(
                        default=dict,
                        help_text="Sentiment analysis results and distribution",
                    ),
                ),
                (
                    "tags_analysis",
                    models.JSONField(
                        default=dict, help_text="Tags, keywords, and topic analysis"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="AI-generated recommendations"
                    ),
                ),
                (
                    "agents_used",
                    models.JSONField(
                        default=dict,
                        help_text="Information about AI agents used in analysis",
                    ),
                ),
                (
                    "workflow_info",
                    models.JSONField(
                        default=dict, help_text="Workflow and processing information"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this analysis is the current active one",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific hotel analyzed (null for all hotels)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Analysis Result",
                "verbose_name_plural": "AI Analysis Results",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis_type", "created_at"],
                        name="reviews_aia_analysi_ba4b02_idx",
                    ),
                    models.Index(
                        fields=["hotel", "created_at"],
                        name="reviews_aia_hotel_i_3d43a8_idx",
                    ),
                    models.Index(
                        fields=["is_active", "analysis_type"],
                        name="reviews_aia_is_acti_1167c7_idx",
                    ),
                    models.Index(
                        fields=["date_range_start", "date_range_end"],
                        name="reviews_aia_date_ra_f11da2_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("days_analyzed__gte", 1), ("days_analyzed__lte", 365)
                        ),
                        name="valid_days_analyzed_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total_reviews_analyzed__gte", 0)),
                        name="valid_reviews_count",
                    ),
                ],
            },
        ),
    ]
