# Generated by Django 5.2.6 on 2025-10-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_aianalysisresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aianalysisresult",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("combined", "Combined Analysis"),
                    ("summary", "Summary Only"),
                    ("sentiment", "Sentiment Analysis"),
                    ("tags", "Tags Analysis"),
                ],
                db_index=True,
                default="combined",
                help_text="Type of AI analysis performed",
                max_length=50,
            ),
        ),
    ]
