# Generated by Django 4.2.7 on 2025-10-17 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Hotel Manager'), ('viewer', 'Viewer')], default='viewer', help_text='User role for permission management', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or position', max_length=100)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='Last login IP address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(blank=True, help_text='Primary hotel association', null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.hotel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['role'], name='user_profil_role_fa03e1_idx'), models.Index(fields=['hotel'], name='user_profil_hotel_i_91cf0b_idx')],
            },
        ),
    ]
